'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Lesson
    Public Property CustomerLogin As String
    Public Property FirstName As String
    Public Property [Date] As Date
    Public Property Hour As String
    Public Property description As String
    Public Property Duration As String

    Public Overridable Property Kid As Kid
    Public Overridable Property LessonDate As LessonDate

End Class
